version: "3.7"

services:
  aaabbb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aaabbb
    restart: always
    ports:
      - "8083:8080"
    environment:
      DATABASE_URL: postgresql://aaabbb_user:qwert@aaabbb-postgres:5432/aaabbb_db
    networks:
      - iotnetwork
    labels:
      - traefik.enable=true
      - traefik.http.routers.aaabbb.rule=Host(`aaabbb.ernilabs.com`)
      - traefik.http.routers.aaabbb.tls=true
      - traefik.http.routers.aaabbb.tls.certresolver=lets-encrypt
      - traefik.http.services.aaabbb.loadbalancer.server.port=8080
    depends_on:
      - aaabbb-postgres

  aaabbb-postgres:
    image: postgres:16-alpine
    container_name: aaabbb_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: aaabbb_user
      POSTGRES_PASSWORD: qwert
      POSTGRES_DB: aaabbb_db
    volumes:
      - aaabbb_postgres_data:/var/lib/postgresql/data
    networks:
      - iotnetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aaabbb_user -d aaabbb_db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  iotnetwork:
    external: true

volumes:
  aaabbb_postgres_data:
