version: "3.7"

services:
  actfinal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: actfinal
    restart: always
    ports:
      - "8083:8080"
    environment:
      DATABASE_URL: postgresql://actfinal_user:qwert@actfinal-postgres:5432/actfinal_db
    networks:
      - iotnetwork
    labels:
      - traefik.enable=true
      - traefik.http.routers.actfinal.rule=Host(`actfinal.ernilabs.com`)
      - traefik.http.routers.actfinal.tls=true
      - traefik.http.routers.actfinal.tls.certresolver=lets-encrypt
      - traefik.http.services.actfinal.loadbalancer.server.port=8080
    depends_on:
      - actfinal-postgres

  actfinal-postgres:
    image: postgres:16-alpine
    container_name: actfinal_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: actfinal_user
      POSTGRES_PASSWORD: qwert
      POSTGRES_DB: actfinal_db
    volumes:
      - actfinal_postgres_data:/var/lib/postgresql/data
    networks:
      - iotnetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U actfinal_user -d actfinal_db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  iotnetwork:
    external: true

volumes:
  actfinal_postgres_data:
