http:
  middlewares:
    simpleAuth:
      basicAuth:
        users:
          - 'admin:$your-password-here'
  routers:
    api:
      rule: Host(`traefik.ernilabs.com`)
      entrypoints:
        - websecure
      middlewares:
        - simpleAuth
      service: api@internal
      tls:
        certResolver: lets-encrypt