entryPoints:
  iotnetwork:
    address: ':81'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
api:
  dashboard: true
certificatesResolvers:
  lets-encrypt:
    acme:
      email: your-email-here@example.com
      storage: /cert/acme.json
      tlsChallenge: {}
providers:
  docker:
    watch: true
    network: iotnetwork
  file:
    filename: traefik_api.yml